# DATA ANALYSIS WITH PANDAS
Topics to be covered:
- Introducton to Data Analysis with Python.
- Pandas DataFrames and Series.
- Data Cleaning with Pandas.
- Aggregating, Reshaping and Combining DataFrames.

## Introducton to Data Analysis with Python
**What is Data Analysis?**

Its the process of examining Data to find patterns, answer questions and make decisions. For example a number becomes useful when we understand what it measures, a waiting time of 20 means nothing until we know the unit is in minutes and thus the record describes one clinic visit. 

Data Science is a field that uses data, statistics, domain knowledge and programming to investigate questions and come up with relevant solutions. Data analysis thus becomes a part of this work.

There are four common types of analysis:
- ***Descriptive Analysis:*** Descriptives tell us what happened, for example how many patient visits were recorded per clinic.
- ***Diagnostics Analysis:*** Tells us why it happened, for example busy patient arrival periods might result to longer wait times.
- ***Predictive Analysis:*** Tells us what might happen, for example how many patient visits might be expected next week.
- ***Prescriptive Analysis:*** Tells us what should be done or what action should be taken, for example which staffing plan could reduce patient waiting times.

**Analysis WorkFLow**
- State a question.
- Get/Obtain/Load the Data.
- Inspecting the Data: Checking for null values, duplicate values, outliers/extreme values, Data types, Data size(how many rows vs columns) and erroneous values e.t.c
- Clean the Data.
- Analyze and visualize.
- Interpret and communicate the results.

**Pandas**
Its a Python Library for working with tabular data ( rows and columns).</br> It can read files, perform data cleaning, perform aggregation functions and combine tables.</br> Its main structure is the ***Series*** and ***DataFrame***. 

The file formats that Pandas reads are the CSV,JSON, Excel, SQL.

We install Pandas by typing the following commands:
- In CONDA environments: ***conda install pandas***
- In Python envs: ***pip install pandas***
- Inline inside Jupyter Notebook: ***! pip install pandas***

## Pandas Series and DataFrames

**Series**</br>
This is a one dimensional labelled collection of values. Think of it as a column together with its rows.

In [2]:
import pandas as pd # pd is an alias

# Pandas Series
age = pd.Series([22,34,27,44,19], name = 'age') # 'name= ' gives the series a descriptive name e.g age, minutes etc
age

0    22
1    34
2    27
3    44
4    19
Name: age, dtype: int64

In [3]:
#create a series that stores temperature. 
temperature = pd.Series([12,24,45,8,40], index=['Monday','Tuesday','Wednesday','Thursday','Friday'], name='temperature')
temperature

Monday       12
Tuesday      24
Wednesday    45
Thursday      8
Friday       40
Name: temperature, dtype: int64

**DataFrames**</br>Its a two dimensional labelled table with rows and columns i.e like an Excel sheet which is a collection of multiple series (has multiple rows and multiple columns).For example data that has name, age and county.

In [4]:
#create a dictionary.
students = {
    'name': ['John','Mary','Peter'],
    'age' : [22, 34, 27],
    'county': ['Nairobi','Mombasa','Kisumu']
    }

print(students)

#turn it into a DataFrame
df = pd.DataFrame(students)
df

{'name': ['John', 'Mary', 'Peter'], 'age': [22, 34, 27], 'county': ['Nairobi', 'Mombasa', 'Kisumu']}

    name  age   county
0   John   22  Nairobi
1   Mary   34  Mombasa
2  Peter   27   Kisumu

In [5]:
# TO DO:
# 1. Reassign the indexes to 101,102,103 respectively.
df.index = [101, 102, 103]

In [6]:
# 2. Display the number of rows and columns.
print((df.shape))

(3, 3)

In [7]:
# 3. Display the column names.
#print(list(students.keys()))
(df.columns)

Index(['name', 'age', 'county'], dtype='object')

In [8]:
# 4. Check the data types.
df.dtypes

name      object
age        int64
county    object
dtype: object

In [9]:
# 5. Display the current indexes.
df.index

Int64Index([101, 102, 103], dtype='int64')

In [10]:
# 6. Select one column (e.g name or any of your choice).

df['age']

101    22
102    34
103    27
Name: age, dtype: int64

In [11]:
# 7. Select two columns.
df[['name','age']] #why the two square brackets?

      name  age
101   John   22
102   Mary   34
103  Peter   27

In [ ]:
# 8. Select a specific row.
df.loc[102] #.loc is label based using label of the column or label of index.

name         Mary
age            34
county    Mombasa
Name: 102, dtype: object

In [ ]:
# 9. Display the third student using their row position.
student=df.iloc[2:3] #.iloc is position based using the row position or column position.
print(student)

    student_name  age home_county
103        Peter   27      Kisumu

In [20]:
# 10. Select the first two rows and first two columns.
df.iloc[0:2,0:2]

    student_name  age
101         John   22
102         Mary   34

In [15]:
# 11. Diplay the names and ages of students older than 30.
df[df['age']>30][['name','age']]

     name  age
102  Mary   34

In [16]:
# 12. Rename the column 'name' to 'student_name' and 'county' to 'home_county'.
df.rename(columns={'name':'student_name','county':'home_county'}, inplace=True)

In [17]:
print(df)

    student_name  age home_county
101         John   22     Nairobi
102         Mary   34     Mombasa
103        Peter   27      Kisumu

In [ ]:
#Further reading