# DATA CLEANING WITH PANDAS
**What is Data Cleaning?**</br>Data cleaning is the process of identifying and addressing problems that make data unreliable/difficult to analyse. Common data cleaning problems include:
- Missing values
- Duplicate values
- Inconsistent Text
- Incorrect Data Types
- Invalid Values

An outlier which is an unusually high or low value compared to the observation is not automatically an error. For example,if the patient wait time is normally between 10 mins to 15 mins but there is a recorded value of a 90 mins wait time,this is clearly an outlier but that does not mean its erroneous.We will end up deciding whether to drop or retain the value\outlier.However, a negative age value violates the meaning of that column denoting that its erroneous.

**Data Cleaning Process**
- Preserve the raw Data and create a working copy.
- Inspect the Data cleaning issues: missing values, duplicate values, erroneous values, column inconsistencies, null values e.t.c
- Deal with the issues example dropping null values, imputations, introduce uniformity e.t.c
- Save the cleaned copy.

In [ ]:
# Step 1: Load Data
import pandas as pd
clinics_visits = pd.read_csv('clinic_visits_raw.csv')
# Preview Data
clinics_visits.head()

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
0,V001,P01,C01,2026-01-05,24.0,consultation,1200,30.0
1,V002,P02,C02,2026-01-05,35.0,LAB,800,45.0
2,V003,P03,C01,2026-01-06,NaN,Consultation,1200,25.0
3,V004,P04,C03,2026-01-06,42.0,Pharmacy,500,15.0
4,V005,P05,C02,2026-02-03,29.0,consultation,1200,NaN

In [7]:
# Step 2: Make a copy of the Raw Data
clinics_visits_copy = clinics_visits.copy()
clinics_visits_copy.head()

,visit_id,patient_id,clinic_id,visit_date,age,service,fee_kes,wait_minutes
0,V001,P01,C01,2026-01-05,24.0,consultation,1200,30.0
1,V002,P02,C02,2026-01-05,35.0,LAB,800,45.0
2,V003,P03,C01,2026-01-06,NaN,Consultation,1200,25.0
3,V004,P04,C03,2026-01-06,42.0,Pharmacy,500,15.0
4,V005,P05,C02,2026-02-03,29.0,consultation,1200,NaN

In [ ]:
# """ 
# Data Cleaning Steps:
# 1. Check for Duplicate and Missing Values
# 2. Drop duplicates and Drop/Impute missing values
# 3. Check and handle outliers
# 4. Check Data Types.
# 5. Standardize column names
# """
# #Step 3: Check for Data Types
print(clinics_visits_copy.dtypes)

# Step 4: Inspect for null/missing and duplicate values
print(clinics_visits_copy.isnull().sum())
print('\n\n')
print(clinics_visits_copy.isna().sum())
print('\n\n')
print(clinics_visits_copy.duplicated().sum())
# #The positive output values shows presence of null values hence cleaning is needed.
# # TO DO : Read on the difference between .isna and .isnull

1

In [ ]:
# Identify the duplicated row.

In [ ]:
#Remove the exact duplicates

In [ ]:
# Step 5: Standardize the Columns (Remove white spaces and consistent naming)

In [ ]:
# Step 6: Convert data types for the following columns: fees(int) and date(datetime)

In [ ]:
# Step 7: Check for invalid ages and missing times.

In [ ]:
# Step 8: Choose between retaining, dropping and filling (imputing)

In [ ]:
# Step 9: Validate the cleaned Data and export(save) it as a CSV file.